#!/bin/bash

open_command () {
  local open_cmd
  case "$OSTYPE" in
    (darwin*) open_cmd='open'  ;;
    (cygwin*) open_cmd='cygstart'  ;;
    (linux*) ! [[ $(uname -a) =~ "Microsoft" ]] && open_cmd='xdg-open' || {
        open_cmd='cmd.exe /c start ""'
        [[ -e "$1" ]] && {
          1="$(wslpath -w "${1:a}")"  || return 1
        }
      } ;;
    (msys*) open_cmd='start ""'  ;;
    (*) echo "Platform $OSTYPE not supported"
      return 1 ;;
  esac
  if [[ "$OSTYPE" == darwin* ]]; then
    ${=open_cmd} "$@" &> /dev/null
  else
    nohup ${=open_cmd} "$@" &> /dev/null
  fi
}

main() {
  local url

  url=$(git remote get-url origin) || return

  if [[ $url == *\@* ]]; then
    url="https://$(git remote get-url origin | awk -F '@' '{ print $2 }' | sed -e 's/:/\//g')"
  fi

  open_command "$url"
}

main
