#!/bin/bash

main() {
  local url new_url

  url=$(git remote get-url origin)

  if [[ $url != http* ]]; then
    echo "This repo's url is already useing ssh."
    return
  fi

  new_url=git@github.com:$(git remote get-url origin | cut -d "/" -f 4,5)

  echo "Change $url to $new_url"
  read -r -p "Confirm [Y/n]: " result

  if [[ $result == "N" || $result == "n" ]]; then
    echo "Cancel by user."
    return
  fi

  git remote set-url origin "$new_url"
  echo "Done"
}

main
