#!/bin/bash

main() {
  if [ "$1" == "" ]; then
    echo "No kind input."
    return
  fi

  res=$(curl -s "https://raw.githubusercontent.com/github/gitignore/master/$1.gitignore")

  if [ "$res" == "404: Not Found" ]; then
    echo "Can not find this kind of gitignore."
    exit
  fi

  echo "$res" > .gitignore
  echo "Add $1's ignore success."
}

main "$1"
