#!/usr/bin/env python3
import sys
import json
import binascii

from base64 import urlsafe_b64decode

jwt = sys.argv[1] if len(sys.argv) > 1 else input()

try:
    header, payload, _ = jwt.split('.')
except ValueError:
    print('Invalid token.')
    exit(1)

try:
    header = urlsafe_b64decode(header).decode('utf-8')
    payload = urlsafe_b64decode(payload).decode('utf-8')
except binascii.Error:
    print('Decode error.')
    exit(1)

header = json.loads(header)
payload = json.loads(payload)

print(json.dumps(
    obj={'header': header, 'payload': payload},
    ensure_ascii=False,
    indent=2,
))
