#!/usr/bin/env python3
import sys
import json

from urllib.parse import urlparse, parse_qs

url_string = sys.argv[1] if len(sys.argv) > 1 else input()

if '/#/' in url_string:
    url_string = url_string.replace('/#/', '/')

url = urlparse(url_string)

result = {
    'url': f'{url.scheme}://{url.netloc}{url.path}',
    'scheme': url.scheme,
    'host': url.netloc,
    'path': url.path,
    'query': parse_qs(url.query),
}

print(json.dumps(result, indent=2, ensure_ascii=False))
