#!/bin/bash

main() {
  local cmd

  cmd="pip freeze"

  for f in "requirements.txt" `[[ -d "requirements" ]] && find requirements -type f -name '*.txt'` "$@"; do
    if [[ ! -f $f ]]; then
      continue
    fi

    cmd="${cmd} -r ${f}"
  done

  echo "${cmd}" | "$SHELL"
}

main $@
